######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 12 13:57:32 2010
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../include
QT += network

# Input
HEADERS += ../chunk.hh
SOURCES += testFEC.cc
