######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 16 16:44:49 2010
######################################################################

QT += network
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../include
INCLUDEPATH += . ../include

# Input
HEADERS += decoder.hh
SOURCES += decoder.cc main.cc
