######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 12 11:43:44 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += chunk.hh udpRelay.hh
SOURCES += main.cc udpRelay.cc
