######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 17 16:51:49 2010
######################################################################

QT += network
CONFIG += qt debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += udpRelay.hh
SOURCES += spliter.cc udpRelay.cc
