######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 15 12:40:44 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ../include
INCLUDEPATH += . ../include
QT += network

# Input
SOURCES += main.cc
