######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 3 14:08:38 2010
######################################################################

QT += network
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../include
INCLUDEPATH += . ../include

# Input
HEADERS += decoder.hh config.hh mainWindow.hh
SOURCES += decoder.cc main.cc mainWindow.cc
