######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 16 15:38:53 2010
######################################################################

QT += network
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../include
INCLUDEPATH += . ../include
LIBS += -lpcap

# Input
HEADERS += checksocket.hh device.hh encoder.hh
SOURCES += checksocket.cc device.cc main.cc encoder.cc
