######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 10 16:26:09 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
CONFIG += qt debug

# Input
HEADERS += udpRelay.hh packetInfo.hh
SOURCES += emulator.cc udpRelay.cc
