######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 19 13:21:35 2010
######################################################################

QT += network
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../include
INCLUDEPATH += . ../include
LIBS += -lpcap

# Input
HEADERS += sender.hh scheduler.hh listener.hh
SOURCES += sender.cc scheduler.cc listener.cc main.cc
