######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 13 14:46:07 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
SOURCES += main.cc
