######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 13 14:46:07 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ../include
INCLUDEPATH += . ../include
LIBS += -lpcap
QT += network

# Input
HEADERS += device.hh checksocket.hh
SOURCES += main.cc device.cc checksocket.cc
