######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 21 20:18:46 2010
######################################################################

QT += network
QT -= gui
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../include

# Input
HEADERS += decoder.hh listener.hh
SOURCES += decoder.cc main.cc listener.cc
