######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 11 10:44:45 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += recorder.hh gettime.hh
SOURCES += main.cc recorder.cc
