######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 18 14:17:02 2010
######################################################################

QT += network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cc
