######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 21 17:57:05 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../include
QT += network
QT -= gui

# Input
HEADERS += encoder.hh listAddr.hh splitter.hh
SOURCES += encoder.cc main.cc splitter.cc
