######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 19 15:20:38 2010
######################################################################

QT += network
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../include
INCLUDEPATH += . ../include
LIBS += -lpcap

# Input
HEADERS += sender.hh
SOURCES += main.cc sender.cc
