######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 18 17:27:10 2010
######################################################################

QT += network

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cc
